import GlobalNav from "@/components/globalNav";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={`${inter.className} flex min-h-screen flex-col items-center justify-between p-24`}
      >
        <GlobalNav />
        {children}
        <footer className='bg-slate-950 p-12 rounded-lg flex-col'>
          <p>Some type of footer</p>
        </footer>
      </body>
    </html>
  );
}
